name: Daily Hotel Price Scraper

on:
  schedule:
    - cron: "0 0 * * *"  # हर दिन आधी रात को
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
          DAYS_TO_REPORT: ${{ secrets.DAYS_TO_REPORT }}
          DELAY: ${{ secrets.DELAY }}
        run: |
          python scrape.pyname: Daily Hotel Price Scraper

on:
  schedule:
    - cron: "0 0 * * *"  # हर दिन आधी रात को
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
          DAYS_TO_REPORT: ${{ secrets.DAYS_TO_REPORT }}
          DELAY: ${{ secrets.DELAY }}
        run: |
          python scrape.py
