
name: Daily Hotel Price Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # रोज़ सुबह 2 बजे UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python scrape.pyname: Daily Hotel Price Scrape

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # रोज़ सुबह 2 बजे UTC

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python scrape.py
